name: Deploy Page

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build_node:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            -   uses: actions/checkout@v2
            -   name: Set Branch
                id: vars
                run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node-version }}

            -   name: Cache CI node_modules
                uses: actions/cache@v2
                env:
                    cache-name: cache-node-modules
                with:
                    # npm cache files are stored in `~/.npm` on Linux/macOS
                    path: ~/.npm
                    key: ${{ runner.os }}-build-${{ env.cache-name }}
            -   name: Prepare Page
                run: |
                    npm ci

            -   name: Build Page
                run: |
                    npm run build
                    cp -r build/media build/defaultPage/media

        # todo: add your deployment steps
